//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URPGDesktopCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URPGDesktopCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _625 {
            get {
                object obj = ResourceManager.GetObject("_625", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO/(none)
        ///AD/Adaptability 
        ///AE/Aerilate
        ///AF/Aftermath * 
        ///AI/Air Lock
        ///AL/Analytic *
        ///AP/Anger Point * 
        ///AN/Anticipation * 
        ///AT/Arena Trap *
        ///AR/Aroma Veil *
        ///AU/Aura Break
        ///BD/Bad Dreams * 
        ///BT/Battery *
        ///BA/Battle Armor * 
        ///BB/Battle Bond *
        ///BEB/Beast Boost *
        ///BZ/Berzerk *
        ///BP/Big Pecks *
        ///BL/Blaze 
        ///BU/Bulletproof *
        ///CP/Cheek Pouch *
        ///CL/Chlorophyll 
        ///CB/Clear Body * 
        ///CN/Cloud Nine 
        ///CC/Color Change * 
        ///CT/Comatose *
        ///CM/Competitive *
        ///CE/Compoundeyes * 
        ///CO/Contrary *
        ///CR/Corrosion *
        ///CY/Cursed Body * [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/DK,GR,PS/FA,FI,FR,FL,GH,PO,S/
        ///DK/GH,PS/DK,FA,FI/
        ///DR/DR/S/FA
        ///E/FL,W/DR,E,GR/GD
        ///FA/DK,DR,FI/FR,PO,S/
        ///FI/DK,I,NM,R,S/B,FA,FL,PO,PS/GH
        ///FR/B,GR,I,S/DR,FR,R,W/
        ///FL/B,FI,GR/E,R,S/
        ///GH/GH,PS/DK/NM
        ///GR/GD,R,W/B,DR,FR,FL,GR,PO,S/
        ///GD/E,FR,PO,R,S/B,GR/FL
        ///I/DR,FL,GR,GD/FR,I,S,W/
        ///NM//R,S/GH
        ///PO/FA,GR/GH,GD,PO,R/S
        ///PS/FI,PO/PS,S/DK
        ///R/B,FR,FL,I/FI,GD,S/
        ///S/FA,I,R/E,FR,S,W/
        ///W/FR,GD,R/DR,GR,W/.
        /// </summary>
        internal static string Compatibilities {
            get {
                return ResourceManager.GetString("Compatibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abomasnow/I/GR/384/283/249/283/269/219
        ///Abomasnow-Mega/GR/I/384/363/309/363/309/159
        ///Abra/PS/NO/254/139/129/309/209/279
        ///Absol/DK/NO/334/359/219/249/219/249
        ///Absol-Mega/DK/NO/334/399/219/329/219/329
        ///Accelgor/B/NO/364/239/179/299/219/389
        ///Aegislash-Blade/S/GH/324/399/199/399/199/219
        ///Aegislash-Shield/S/GH/324/199/399/199/399/219
        ///Aerodactyl/R/FL/364/309/229/219/249/359
        ///Aerodactyl-Mega/R/FL/364/369/269/239/289/399
        ///Aggron/S/R/344/319/459/219/219/199
        ///Aggron-Mega/S/NO/344/379/559/219/259/199
        ///Aipom/NM/NO/314 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO/(none)
        ///B/Bug
        ///DK/Dark
        ///DR/Dragon
        ///E/Electric
        ///FA/Fairy
        ///FI/Fighting
        ///FR/Fire
        ///FL/Flying
        ///GH/Ghost
        ///GR/Grass
        ///GD/Ground
        ///I/Ice
        ///NM/Normal
        ///PO/Poison
        ///PS/Psychic
        ///R/Rock
        ///S/Steel
        ///W/Water.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
